### PR TITLE
fixes #11

### LINKED ISSUE #11: Getting this error on a Fresh install of QB-Core for RedM
[script:qbr-smallreso] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export GetPlayers in resource qbr-core

### PR DESCRIPTION
**Pull request by atarifeels**
image

### CODE REVIEW

**Comment by zachdhunt** [comment]
Now i am proceeding to get this : [script:qbr-smallreso] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export GetPermission in resource qbr-core 
&
[ citizen-server-impl] Server list query returned an error: System.Threading.Tasks.TaskCanceledException: The operation was canceled. <- System.TimeoutException: The operation was canceled. <- System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.

i have had multiple issues with this, cannot use the character creation screen. froze in a bush when i spawn with no inputs, having to Quit out, then i will spawn back, with just pants, no body at all.

**Comment by zachdhunt** [comment]
Now : [script:qbr-multichar] SCRIPT ERROR: Execution of native 00000000406b4b20 in script host failed: Argument at index 0 was null.

**Comment by zachdhunt** [comment]
[script:qbr-multichar] SCRIPT ERROR: @qbr-multicharacter/server/main.lua:115: attempt to index a nil value (field 'integer index')

**Comment by zachdhunt** [comment]
upon fixing this, i got this now. at this point im just posting these errors. 
[script:qbr-core] (nil stack trace)SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export GetPlayers in resource qbr-core

**Comment by zachdhunt** [comment]
[script:qbr-scoreboar] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export GetPlayers in resource qbr-core

**Comment by atarifeels** [comment]
> [ citizen-server-impl] Server list query returned an error: System.Threading.Tasks.TaskCanceledException: The operation was canceled. <- System.TimeoutException: The operation was canceled. <- System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.

This is what I don't understand. I'm getting this as well! Not sure how to fix it, updated artifacts and didn't help.

**Comment by GhzGarage** [comment]
I think it has to do with your firewall

**Comment by atarifeels** [comment]
> I think it has to do with your firewall

Yeah I know. I'll try to do something with artifacts.

**Pull request merged**
